// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXPBZxsGDHpwuCHer9Ik9saUTeWqmJnBc',
    appId: '1:667112847725:web:a13eaa4c6fe00bb6ed8264',
    messagingSenderId: '667112847725',
    projectId: 'maya-efe1e',
    authDomain: 'maya-efe1e.firebaseapp.com',
    storageBucket: 'maya-efe1e.firebasestorage.app',
    measurementId: 'G-HE06EHLHER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYunrWh5gvLnl_bOxmhTA6CV2iYtAATX0',
    appId: '1:667112847725:android:bad1cd98ea6f38b3ed8264',
    messagingSenderId: '667112847725',
    projectId: 'maya-efe1e',
    storageBucket: 'maya-efe1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKrMtV08MrGWQvbVUETPaTWtO2wMTZ81Q',
    appId: '1:667112847725:ios:7a673fdb8764cde4ed8264',
    messagingSenderId: '667112847725',
    projectId: 'maya-efe1e',
    storageBucket: 'maya-efe1e.firebasestorage.app',
    iosBundleId: 'com.yourcompany.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKrMtV08MrGWQvbVUETPaTWtO2wMTZ81Q',
    appId: '1:667112847725:ios:7a673fdb8764cde4ed8264',
    messagingSenderId: '667112847725',
    projectId: 'maya-efe1e',
    storageBucket: 'maya-efe1e.firebasestorage.app',
    iosBundleId: 'com.yourcompany.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXPBZxsGDHpwuCHer9Ik9saUTeWqmJnBc',
    appId: '1:667112847725:web:4597cd6fad2cba98ed8264',
    messagingSenderId: '667112847725',
    projectId: 'maya-efe1e',
    authDomain: 'maya-efe1e.firebaseapp.com',
    storageBucket: 'maya-efe1e.firebasestorage.app',
    measurementId: 'G-M29154D4JW',
  );
}
